### ISSUE TITLE
Can't seem to get pass/fail to upload to TestLink

### ISSUE THREAD

**Issue by cgestido** [parthibann/Python-TestLink-Runner#2]
Hey.

I know this project is a few years old, but I was trying to get my python unittest results uploaded to TestLink and I'm having some issues.

My script is actually using android's monkeyrunner cmds, and it looks like this:

```
import unittest
import TestLinkRunner
from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice
device = MonkeyRunner.waitForConnection()


class TestOne(unittest.TestCase):
    def test_one(self):
        pass

if __name__ == '__main__':
  unittest.main()

testlinkURL = "http://MYTESTLINKHOST/testlink/lib/api/xmlrpc/v1/xmlrpc.php"
userKey = "MYKEY"
suite = unittest.TestLoader().loadTestsFromTestCase(TestOne)
runner = TestLinkRunner(testlinkURL,userKey,_testPlanId=1324,_buildName="test")
runner.run(suite)

```

The tests pass when I run them, but I don't see the results in testlink. I added the test with the corresponding testPlanId into the build "test" which is in the test plan of the same name. Do I need to name the test something specific to get upload to work? Are there logs anywhere that can tell me why the upload is failing?

I don't see any errors.. The test just passes and that's it.

Any help would be appreciated.
Thanks,
Cory

**Comment by parthibann** [comment]
You have to specify the testcase_id (testlink testcase api_id) in the testcase function.
e.g:
class TestOne(unittest.TestCase):
    def test_1_one(self):
        pass

in the above function name "test_1_one", "test" is the keyword used for specifying this method is a testcase, "1" is the testcase api id which is provided by testlink and then followed by testcase name.

Follow the instructions specified here.
https://github.com/parthibann/Python-TestLink-Runner/wiki/How-to-use-Python-TestLink-Runner
